language: python
python:
  - "2.7"
addons:
  apt:
    packages:
    - cmake
    - pytest
before_install:
  - pip install pika==0.9.13 paho-mqtt avro kafka-python hl7apy simplejson
  - git clone https://github.com/crs4/pyavroc.git /tmp/pyavroc
  - sed -i 's/[ -d $AVRO ] || git clone -b patches http:\/\/github.com\/Byhiras\/avro $(basename $AVRO)/[ -d $AVRO ] || git clone -b fix_c_default http:\/\/github.com\/crs4\/avro $(basename $AVRO)/g' /tmp/pyavroc/clone_avro_and_build.sh
  - /tmp/pyavroc/clone_avro_and_build.sh
  - export PYTHONPATH=/tmp/pyavroc/build/lib.linux-x86_64-2.7/:/tmp/pyavroc/build/lib.linux-x86_64-2.7/pyavroc
services:
  - rabbitmq
before_script:
  - sudo rabbitmq-plugins enable rabbitmq_mqtt
  - sudo service rabbitmq-server restart
install:
  - python setup.py install
script:
  - nosetests tests clay
branches:
  only:
    - develop